DEF_CMD_REGS
DEF_CMD_PUSH_POP(PUSH)
DEF_CMD_PUSH_POP(POP)
DEF_CMD_OTHERS(ADD)
DEF_CMD_OTHERS(SUB)
DEF_CMD_OTHERS(MUL)
DEF_CMD_OTHERS(DIV)
DEF_CMD_OTHERS(OUT)
DEF_CMD_OTHERS(HLT)
DEF_CMD_OTHERS(SQRT)
DEF_CMD_OTHERS(RET)

DEF_CMD_JMPS("JMP", JMP)
DEF_CMD_JMPS("JZ", JZ) 
DEF_CMD_JMPS("JE", JE) 
DEF_CMD_JMPS("JG", JG) 
DEF_CMD_JMPS("JNE", JNE) 
DEF_CMD_JMPS("JGE", JGE) 

DEF_CMD_WITH_REG("DEC", DEC)
DEF_CMD_WITH_REG("INC", INC)
DEF_CMD_WITH_REG("INP", INP)
DEF_CMD_WITH_REG("PRT", PRT)
DEF_CMD_CALL
DEF_CMD_FUNC
DEF_CMD_FLAG
CMD_ERROR_TOKEN